[project]
name = "tuto-django-in-git-branches"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django-debug-toolbar>=5.1.0",
    "django>=5.2",
]
